name: CI

on: 
  push:
  
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@v0.7.1
        with:
          local:  /home/runner/work/coordinator/coordinator/
          remote: /var/www/erp-server.ru
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: cd /var/www/erp-server.ru; ls -l
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
